### ISSUE TITLE
Not working (anymore?) with GA31

### ISSUE THREAD

**Issue by ferdez** [ruben-pulido/player#17]
I've been trying to follow your demo from last year's dev/24 and am unable to make this work. 

Then I just deployed your full module and it also doesn't work. :-(

When I go to Collections / Show Items I get a message like "${processor.processMax()}" and, on the server log:

java.lang.NoClassDefFoundError: Could not initialize class com.liferay.player.web.internal.info.item.fields.PlayerInfoFields

Am I missing something or did Liferay just move on and made this code obsolete?

TIA

**Comment by ruben-pulido** [comment]
Hi @ferdez!

Thanks for the heads up. There have been some non backwards compatible changes in InfoField that caused the code not to work any longer.

This [commit](https://github.com/ruben-pulido/player/commit/400fb60f7713af2e3090d2ba4afe3db542ad40e8) upgrades the code to 7.4-ga31. Now it should work again.
